# FunctionsReqVersions
# Declares the minimum required version of each function needed by this datagram.
# SemVer format (major.minor.patch).

[Datagram Loader Version]=1.0.0
[Image Viewer Version]=1.0.0
[Buttons Version]=1.0.0
